/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cachitodelivery;

/**
 *
 * @author cusi
 */
public class Agregar_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_cliente
     */
    public Agregar_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTApellido = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTDescripcion = new javax.swing.JTextField();
        jTPais = new javax.swing.JTextField();
        jTArea = new javax.swing.JTextField();
        jTtelefono = new javax.swing.JTextField();
        jBAgregarTel = new javax.swing.JButton();
        jBQuitarTel = new javax.swing.JButton();
        jTDni = new javax.swing.JTextField();
        jBRegistrar = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        JL_Usuario_admin1 = new javax.swing.JLabel();
        JL_Fecha_Admin1 = new javax.swing.JLabel();
        JL_Hora_Admin1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTApellido1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTNombre1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTDni1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTDescripcion1 = new javax.swing.JTextField();
        jTPais1 = new javax.swing.JTextField();
        jTArea1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTApellido.setToolTipText("");
        jTApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidoActionPerformed(evt);
            }
        });

        jTNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTNombre.setToolTipText("");
        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });

        jTDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTPais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTPais.setText("54");
        jTPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPaisActionPerformed(evt);
            }
        });
        jTPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPaisKeyTyped(evt);
            }
        });

        jTArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTArea.setText("383");
        jTArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTAreaKeyTyped(evt);
            }
        });

        jTtelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTtelefonoKeyTyped(evt);
            }
        });

        jBAgregarTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Telefono.png"))); // NOI18N
        jBAgregarTel.setBorder(null);
        jBAgregarTel.setBorderPainted(false);
        jBAgregarTel.setContentAreaFilled(false);
        jBAgregarTel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregarTel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Telefono_hover.png"))); // NOI18N
        jBAgregarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarTelActionPerformed(evt);
            }
        });
        jBAgregarTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBAgregarTelKeyPressed(evt);
            }
        });

        jBQuitarTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Quitar.png"))); // NOI18N
        jBQuitarTel.setBorder(null);
        jBQuitarTel.setBorderPainted(false);
        jBQuitarTel.setContentAreaFilled(false);
        jBQuitarTel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBQuitarTel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Quitar_hover.png"))); // NOI18N
        jBQuitarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuitarTelActionPerformed(evt);
            }
        });

        jTDni.setColumns(8);
        jTDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTDniFocusLost(evt);
            }
        });
        jTDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTDniKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDniKeyReleased(evt);
            }
        });

        jBRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Agregar.png"))); // NOI18N
        jBRegistrar.setBorder(null);
        jBRegistrar.setBorderPainted(false);
        jBRegistrar.setContentAreaFilled(false);
        jBRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Agregar_hover.png"))); // NOI18N
        jBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarActionPerformed(evt);
            }
        });
        jBRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBRegistrarKeyPressed(evt);
            }
        });

        jBAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Atras.png"))); // NOI18N
        jBAtras.setBorder(null);
        jBAtras.setBorderPainted(false);
        jBAtras.setContentAreaFilled(false);
        jBAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Atras_hover.png"))); // NOI18N
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });

        JL_Usuario_admin1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Usuario_admin1.setForeground(new java.awt.Color(255, 255, 255));
        JL_Usuario_admin1.setText("USUARIO:");

        JL_Fecha_Admin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_Fecha_Admin1.setForeground(new java.awt.Color(255, 255, 255));
        JL_Fecha_Admin1.setText("FF/FF/FFFF");

        JL_Hora_Admin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_Hora_Admin1.setForeground(new java.awt.Color(255, 255, 255));
        JL_Hora_Admin1.setText("HH:HH");

        jTApellido1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTApellido1.setToolTipText("");
        jTApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellido1ActionPerformed(evt);
            }
        });

        jTNombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTNombre1.setToolTipText("");
        jTNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombre1ActionPerformed(evt);
            }
        });

        jTDni1.setColumns(8);
        jTDni1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTDni1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTDni1FocusLost(evt);
            }
        });
        jTDni1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTDni1KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDni1KeyReleased(evt);
            }
        });

        jTDescripcion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTPais1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTPais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPais1ActionPerformed(evt);
            }
        });
        jTPais1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPais1KeyTyped(evt);
            }
        });

        jTArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTArea1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(jTPais, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTArea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jBQuitarTel)
                                                .addGap(112, 112, 112)
                                                .addComponent(jBAgregarTel)))
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(229, 229, 229)
                                                .addComponent(jBRegistrar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jTDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jTPais1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(12, 12, 12)
                                                            .addComponent(jTArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(jTDni1, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBAtras))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(JL_Usuario_admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_Fecha_Admin1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JL_Hora_Admin1)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_Usuario_admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTPais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBQuitarTel)
                                    .addComponent(jBAgregarTel)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTPais1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(86, 86, 86)
                                .addComponent(jBRegistrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBAtras)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Fecha_Admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_Hora_Admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidoActionPerformed

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jTPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPaisActionPerformed

    private void jTPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPaisKeyTyped
        if((evt.getKeyChar()>'9' || evt.getKeyChar()<'0') && (evt.getKeyChar() != evt.VK_BACK_SPACE))
        evt.consume();
    }//GEN-LAST:event_jTPaisKeyTyped

    private void jTAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAreaKeyTyped
        if((evt.getKeyChar()>'9' || evt.getKeyChar()<'0') && (evt.getKeyChar() != evt.VK_BACK_SPACE))
        evt.consume();
    }//GEN-LAST:event_jTAreaKeyTyped

    private void jTtelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtelefonoKeyTyped
        if((evt.getKeyChar()>'9' || evt.getKeyChar()<'0') && (evt.getKeyChar() != evt.VK_BACK_SPACE))
        evt.consume();
    }//GEN-LAST:event_jTtelefonoKeyTyped

    private void jBAgregarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarTelActionPerformed
//        if(jTtelefono.getText().isEmpty() || jTPais.getText().isEmpty() || jTArea.getText().isEmpty()){
//            JOptionPane.showMessageDialog(rootPane, "No se ingreso un numero de telefono válido.");
//            return;
//        }
//        if(telefono.length==0){
//            telefono = new Object[telefono.length+1][2];
//            telefono[0][0]="+"+jTPais.getText()+jTArea.getText()+jTtelefono.getText();
//            telefono[0][1]=jTDescripcion.getText();
//        }else{
//            for(int i=0;i<telefono.length;i++){
//                if(Objects.equals("+"+jTPais.getText()+jTArea.getText()+jTtelefono.getText(),telefono[i][0])){
//                    JOptionPane.showMessageDialog(rootPane, "El telefono "+"+"+jTPais.getText()+jTArea.getText()+jTtelefono.getText()+
//                        ".\nYa ha sido ingresado.");
//                    return;
//                }
//            }
//
//            Object[][] tel = telefono;
//
//            telefono = new Object[telefono.length+1][2];
//            for(int i=0; i<telefono.length;i++){
//
//                if(i==telefono.length-1){
//                    telefono[i][0]="+"+jTPais.getText()+jTArea.getText()+jTtelefono.getText();
//                    telefono[i][1]=jTDescripcion.getText();
//                }else{
//                    telefono[i][1]=tel[i][1];
//                    telefono[i][0]=tel[i][0];
//                }
//            }
//        }
//
//        Object[][] aux = new Object[telefono.length][2];
//        for(int i=0;i<telefono.length;i++){
//            aux[i][0]=telefono[i][1];
//            aux[i][1]=telefono[i][0];
//        }
//
//        jTable2.setModel(new javax.swing.table.DefaultTableModel(
//            aux,new String[] {"",""}));
//    jTDescripcion.setText("");
//    jTPais.setText("54");
//    jTArea.setText("383");
//    jTtelefono.setText("");
//
    }//GEN-LAST:event_jBAgregarTelActionPerformed

    private void jBAgregarTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBAgregarTelKeyPressed
//        if(evt.getKeyCode() == evt.VK_ENTER){
//            if(jTtelefono.getText().isEmpty() || jTPais.getText().isEmpty() || jTArea.getText().isEmpty()){
//                JOptionPane.showMessageDialog(rootPane, "No se ingreso un numero de telefono válido.");
//                return;
//            }
//            if(telefono.length==0){
//                telefono = new Object[telefono.length+1][2];
//                telefono[0][0]="+"+jTPais.getText()+jTArea.getText()+jTtelefono.getText();
//                telefono[0][1]=jTDescripcion.getText();
//            }else{
//                for(int i=0;i<telefono.length;i++){
//                    if(Objects.equals("+"+jTPais.getText()+jTArea.getText()+jTtelefono.getText(),telefono[i][0])){
//                        JOptionPane.showMessageDialog(rootPane, "El telefono "+"+"+jTPais.getText()+jTArea.getText()+jTtelefono.getText()+
//                            ".\nYa ha sido ingresado.");
//                        return;
//                    }
//                }
//
//                Object[][] tel = telefono;
//
//                telefono = new Object[telefono.length+1][2];
//                for(int i=0; i<telefono.length;i++){
//
//                    if(i==telefono.length-1){
//                        telefono[i][0]="+"+jTPais.getText()+jTArea.getText()+jTtelefono.getText();
//                        telefono[i][1]=jTDescripcion.getText();
//                    }else{
//                        telefono[i][1]=tel[i][1];
//                        telefono[i][0]=tel[i][0];
//                    }
//                }
//            }
//
//            Object[][] aux = new Object[telefono.length][2];
//            for(int i=0;i<telefono.length;i++){
//                aux[i][0]=telefono[i][1];
//                aux[i][1]=telefono[i][0];
//            }
//
//            jTable2.setModel(new javax.swing.table.DefaultTableModel(
//                aux,new String[] {"",""}));
//        jTDescripcion.setText("");
//        jTPais.setText("54");
//        jTArea.setText("383");
//        jTtelefono.setText("");
//        }
    }//GEN-LAST:event_jBAgregarTelKeyPressed

    private void jBQuitarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuitarTelActionPerformed
//        if(jTable2.getSelectedRow()==-1)
//        return;
//
//        String numero=jTable2.getValueAt(jTable2.getSelectedRow(),1).toString();
//        Object[][] tel = telefono;
//        telefono = new Object[telefono.length][2];
//        for(int i=0; i<telefono.length;i++){
//            if(Objects.equals(numero,tel[i][0])){
//                telefono[i][0]=null;
//                telefono[i][1]=null;
//            }else{
//                telefono[i][0]=tel[i][0];
//                telefono[i][1]=tel[i][1];
//            }
//        }
//        tel = telefono;
//        telefono = new Object[telefono.length-1][2];
//
//        int i=0, j=0;
//        while(i<tel.length){
//            if(tel[i][1]==null){
//                i++;
//            }else{
//                telefono[j][0]=tel[i][0];
//                telefono[j][1]=tel[i][1];
//                i++;j++;
//            }
//        }
//
//        Object[][] aux = new Object[telefono.length][2];
//        for(int k=0;k<telefono.length;k++){
//            aux[k][0]=telefono[k][1];
//            aux[k][1]=telefono[k][0];
//        }
//
//        jTable2.setModel(new javax.swing.table.DefaultTableModel(
//            aux,new String[] {"",""}));
    }//GEN-LAST:event_jBQuitarTelActionPerformed

    private void jTDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTDniFocusLost

    }//GEN-LAST:event_jTDniFocusLost

    private void jTDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDniKeyTyped
//        if((evt.getKeyChar()>'9' || evt.getKeyChar()<'0') && (evt.getKeyChar() != evt.VK_BACK_SPACE))
//        evt.consume();
//        if(jTDni.getText().length()>7)
//        evt.consume();

    }//GEN-LAST:event_jTDniKeyTyped

    private void jTDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDniKeyReleased

    }//GEN-LAST:event_jTDniKeyReleased

    private void jBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarActionPerformed
//        if(jTApellido.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null, "No se ingresó un APELLIDO de usuario.");
//            return;
//        }if(jTNombre.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null, "No se ingresó un NOMBRE de usuario.");
//            return;
//        }if(jTDni.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null, "No se ingresó número de DOCUMENTO de usuario.");
//            return;
//        }if(jTContraseña.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null, "No se ingresó una CONTRASEÑA de usuario.");
//            return;
//        }
//        Usuario user = new Usuario();
//        int dni;
//
//        try{
//            dni = Integer.parseInt(jTDni.getText().trim());
//            user.setDni(dni);
//            user.setNombre(jTNombre.getText().trim());
//            user.setApellido(jTApellido.getText().trim());
//            user.setPass(jTContraseña.getText().trim());
//            user.setCargo(jCCargo.getSelectedIndex());
//            user.setActivo(true);
//            user.setFis(fis);
//            user.setLongitud(longitudBytes);
//            GestorUsuario gesus = new GestorUsuario();
//            Telefono_UsuarioDAO tel = new Telefono_UsuarioDAO();
//            UsuarioDAO usuario = new UsuarioDAO();
//            int codigo = usuario.lastUser();
//            Object[][] aux = new Object[telefono.length][3];
//            for(int i=0; i<telefono.length;i++){
//                aux[i][0]=codigo+1;
//                aux[i][1]=telefono[i][0];
//                aux[i][2]=telefono[i][1];
//            }
//            tel.agregarGabe(aux);
//            gesus.agregarNuevoUsuario(user);
//
//            try {
//                clearAgregar();
//            }catch (DataAccessException ex) {Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }catch(NumberFormatException ex ){JOptionPane.showMessageDialog(null, "Solo debe ingresar numeros en el DOCUMENTO.");
//        }catch(TelefonoUsuarioInexistenteException ex){JOptionPane.showMessageDialog(null, ex.getMessage());
//        }catch(DataAccessException ex){JOptionPane.showMessageDialog(null, "Error al Insertar "+ex);
//        }catch(UsuarioExistenteException ex){JOptionPane.showMessageDialog(null, "EL DOCUMENTO de usuario ya fue registrado.");
//            JOptionPane.showMessageDialog(null, "El usuario fue agregado con éxito.");
//        }
    }//GEN-LAST:event_jBRegistrarActionPerformed

    private void jBRegistrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBRegistrarKeyPressed
//        if(evt.getKeyCode() == evt.VK_ENTER){
//            if(jTApellido.getText().isEmpty()){
//                JOptionPane.showMessageDialog(null, "No se ingresó un APELLIDO de usuario.");
//                return;
//            }if(jTNombre.getText().isEmpty()){
//                JOptionPane.showMessageDialog(null, "No se ingresó un NOMBRE de usuario.");
//                return;
//            }if(jTDni.getText().isEmpty()){
//                JOptionPane.showMessageDialog(null, "No se ingresó número de DOCUMENTO de usuario.");
//                return;
//            }if(jTContraseña.getText().isEmpty()){
//                JOptionPane.showMessageDialog(null, "No se ingresó una CONTRASEÑA de usuario.");
//                return;
//            }
//            Usuario user = new Usuario();
//            int dni;
//
//            try{
//                dni = Integer.parseInt(jTDni.getText().trim());
//                user.setDni(dni);
//                user.setNombre(jTNombre.getText().trim());
//                user.setApellido(jTApellido.getText().trim());
//                user.setPass(jTContraseña.getText().trim());
//                user.setCargo(jCCargo.getSelectedIndex());
//                user.setActivo(true);
//                user.setFis(fis);
//                user.setLongitud(longitudBytes);
//                GestorUsuario gesus = new GestorUsuario();
//                Telefono_UsuarioDAO tel = new Telefono_UsuarioDAO();
//                UsuarioDAO usuario = new UsuarioDAO();
//                int codigo = usuario.lastUser();
//                Object[][] aux = new Object[telefono.length][3];
//                for(int i=0; i<telefono.length;i++){
//                    aux[i][0]=codigo;
//                    aux[i][1]=telefono[i][0];
//                    aux[i][2]=telefono[i][1];
//                }
//                tel.agregarGabe(aux);
//                gesus.agregarNuevoUsuario(user);
//
//                try {
//                    clearAgregar();
//                }catch (DataAccessException ex) {Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }catch(NumberFormatException ex ){JOptionPane.showMessageDialog(null, "Solo debe ingresar numeros en el DOCUMENTO.");
//            }catch(TelefonoUsuarioInexistenteException ex){JOptionPane.showMessageDialog(null, ex.getMessage());
//            }catch(DataAccessException ex){JOptionPane.showMessageDialog(null, "Error al Insertar "+ex);
//            }catch(UsuarioExistenteException ex){JOptionPane.showMessageDialog(null, "EL DOCUMENTO de usuario ya fue registrado.");
//                JOptionPane.showMessageDialog(null, "El usuario fue agregado con éxito.");
//            }
//        }
    }//GEN-LAST:event_jBRegistrarKeyPressed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
//        try {
//            clearAgregar();
//            this.h1.stop();
//            JF_Agregar_Usuario.dispose();
//            vtListaEmpleados = new Listado_empleados(cuentaOficial);
//            vtListaEmpleados.clearBusqueda();
//            vtListaEmpleados.iniciarListado();
//            vtListaEmpleados.mostrar(true);
//        } catch (DataAccessException ex) {
//            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jBAtrasActionPerformed

    private void jTApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellido1ActionPerformed

    private void jTNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombre1ActionPerformed

    private void jTDni1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTDni1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDni1FocusLost

    private void jTDni1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDni1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDni1KeyTyped

    private void jTDni1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDni1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDni1KeyReleased

    private void jTPais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPais1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPais1ActionPerformed

    private void jTPais1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPais1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPais1KeyTyped

    private void jTArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTArea1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTArea1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_Fecha_Admin1;
    private javax.swing.JLabel JL_Hora_Admin1;
    private javax.swing.JLabel JL_Usuario_admin1;
    private javax.swing.JButton jBAgregarTel;
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBQuitarTel;
    private javax.swing.JButton jBRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTApellido1;
    private javax.swing.JTextField jTArea;
    private javax.swing.JTextField jTArea1;
    private javax.swing.JTextField jTDescripcion;
    private javax.swing.JTextField jTDescripcion1;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTDni1;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTNombre1;
    private javax.swing.JTextField jTPais;
    private javax.swing.JTextField jTPais1;
    private javax.swing.JTextField jTtelefono;
    // End of variables declaration//GEN-END:variables
}
